[package]
name = "mandelbrot-rayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
image = "0.25.1"
rayon = "1.10.0"
